<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BlazorStrap" Version="5.2.103.250102" />
    <ProjectReference Include="..\SGPP.Domain\SGPP.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\img\" />
  </ItemGroup>

</Project>
